legacy_row <- function(example, chapter, note) {
  data.frame(
    Example = example,
    Chapter = chapter,
    `Book Section` = "absent from 2024 2nd edition as exact numbered example",
    `Output Type` = "Legacy example status",
    `Book Value` = "not in 2nd edition",
    `Package Value` = "legacy topic retained",
    Difference = "",
    Status = "UNVERIF",
    Diagnosis = "Example from 1st edition. Not in 2nd edition.",
    `Action Taken` = paste(
      "Classified as LEGACY after searching the extracted 2024 book text;",
      note,
      "No 2024 book numerical comparison is available under this example number."
    ),
    check.names = FALSE
  )
}

no_export_row <- function(chapter, note) {
  data.frame(
    Example = paste0("Chapter", chapter),
    Chapter = chapter,
    `Book Section` = "package inventory",
    `Output Type` = "No exported Exam function",
    `Book Value` = "not applicable",
    `Package Value` = paste0("no Exam", chapter, ".* object present"),
    Difference = "",
    Status = "UNVERIF",
    Diagnosis = paste0(
      "No exported Chapter ", chapter,
      " example function is present in the package source."
    ),
    `Action Taken` = paste(
      "Searched R/, data/, and vignettes/ for exported example objects;",
      note,
      "No numerical verification row can be produced for a non-existent exported example."
    ),
    check.names = FALSE
  )
}

rows <- rbind(
  no_export_row(15, "Chapter 15 book examples use Data Sets 15.1-15.3, but this package currently has no Chapter 15 data or Exam object."),
  no_export_row(16, "Chapter 16 book examples use smoothing-spline sections, but this package currently has no Chapter 16 data or Exam object."),
  legacy_row("Exam17.1", 17, "The 2024 book labels repeated-measures examples as Example 17.3.1 and 17.3.2 rather than Example 17.1."),
  legacy_row("Exam17.2", 17, "The 2024 book labels repeated-measures examples as Example 17.3.1 and 17.3.2 rather than Example 17.2."),
  legacy_row("Exam18.1", 18, "The 2024 book uses section examples such as 18.2.1; no exact Example 18.1 label matches this package object."),
  legacy_row("Exam18.2", 18, "The 2024 book uses section examples such as 18.2.1; no exact Example 18.2 label matches this package object."),
  no_export_row(19, "Chapter 19 is conceptual/Bayesian prior setup in this package surface; no Exam19 object is exported."),
  no_export_row(20, "Chapter 20 book examples are Bayesian GLMM examples, but this package currently has no Exam20 object or Chapter 20 dataset."),
  legacy_row("Exam21.1", 21, "The 2024 book labels power examples as Example 21.1.1, 21.1.2, 21.3.1, 21.3.2, 21.3.3, 21.4.1, and 21.4.2 rather than Example 21.1."),
  legacy_row("Exam21.2", 21, "The 2024 book labels power examples as Example 21.1.1, 21.1.2, 21.3.1, 21.3.2, 21.3.3, 21.4.1, and 21.4.2 rather than Example 21.2.")
)

utils::write.csv(
  rows,
  "inst/verification/ch15-ch21-verification.csv",
  row.names = FALSE,
  na = ""
)

esc <- function(x) {
  gsub("\\|", "\\\\|", as.character(x))
}
md_table <- function(x) {
  x[] <- lapply(x, esc)
  header <- paste0("| ", paste(names(x), collapse = " | "), " |")
  sep <- paste0("|", paste(rep("---", ncol(x)), collapse = "|"), "|")
  body <- apply(x, 1, function(z) {
    paste0("| ", paste(z, collapse = " | "), " |")
  })
  c(header, sep, body)
}

writeLines(
  c(
    "# Chapter 15-21 Verification Classification",
    "",
    "Generated by inst/verification/ch15-ch21-verification.R.",
    "",
    paste(
      "The remaining package examples either have no exact numbered match in",
      "the 2024 2nd edition or the chapter has no exported package example."
    ),
    "",
    md_table(rows)
  ),
  "inst/verification/ch15-ch21-runtime-verification.md"
)
