legacy_row <- function(example, chapter, note) {
  data.frame(
    Example = example,
    Chapter = chapter,
    `Book Section` = "absent from 2024 2nd edition as exact numbered example",
    `Output Type` = "Legacy example status",
    `Book Value` = "not in 2nd edition",
    `Package Value` = "legacy topic retained",
    Difference = "",
    Status = "UNVERIF",
    Diagnosis = "Example from 1st edition. Not in 2nd edition.",
    `Action Taken` = paste(
      "Classified as LEGACY after searching the extracted 2024 book text;",
      note,
      "No 2024 book numerical comparison is available under this example number."
    ),
    check.names = FALSE
  )
}

rows <- rbind(
  legacy_row(
    "Exam12.1", 12,
    "Chapter 12 uses section examples such as 12.3.1, 12.3.2, and 12.6.2 rather than an exact Example 12.1 label."
  ),
  legacy_row(
    "Exam12.2", 12,
    "Chapter 12 uses section examples such as 12.3.1, 12.3.2, and 12.6.2 rather than an exact Example 12.2 label."
  ),
  data.frame(
    Example = "Chapter13",
    Chapter = 13,
    `Book Section` = "package inventory",
    `Output Type` = "No exported Exam function",
    `Book Value` = "not applicable",
    `Package Value` = "no Exam13.* or DataSet13.* objects present",
    Difference = "",
    Status = "UNVERIF",
    Diagnosis = "No exported Chapter 13 example function or dataset is present in the package source.",
    `Action Taken` = "Searched R/, data/, and vignettes/ for Exam13 and DataSet13 objects; no numerical verification row can be produced for a non-existent exported example.",
    check.names = FALSE
  ),
  legacy_row(
    "Exam14.1", 14,
    "Chapter 14 contains ordinal sections 14.3 and 14.4 but no exact Example 14.1 label matching this package object."
  ),
  legacy_row(
    "Exam14.2", 14,
    "Chapter 14 contains ordinal and nominal sections but no exact Example 14.2 label matching this package object."
  )
)

utils::write.csv(
  rows,
  "inst/verification/ch12-ch14-verification.csv",
  row.names = FALSE,
  na = ""
)

esc <- function(x) {
  gsub("\\|", "\\\\|", as.character(x))
}
md_table <- function(x) {
  x[] <- lapply(x, esc)
  header <- paste0("| ", paste(names(x), collapse = " | "), " |")
  sep <- paste0("|", paste(rep("---", ncol(x)), collapse = "|"), "|")
  body <- apply(x, 1, function(z) {
    paste0("| ", paste(z, collapse = " | "), " |")
  })
  c(header, sep, body)
}

writeLines(
  c(
    "# Chapter 12-14 Verification Classification",
    "",
    "Generated by inst/verification/ch12-ch14-verification.R.",
    "",
    paste(
      "The exported Chapter 12 and 14 package examples do not occur as exact",
      "numbered examples in the 2024 2nd edition. Chapter 13 has no exported",
      "Exam13.* or DataSet13.* objects in this package."
    ),
    "",
    md_table(rows)
  ),
  "inst/verification/ch12-ch14-runtime-verification.md"
)
